#Criando um banco de dados local

Quando falamos sobre banco de dados nos referimos a um sistema de gerenciamento no qual conseguimos armazenar, gerenciar e atualizar dados.

A linguagem trabalhada em banco de dados é a SQL, uma sigla que vem do inglês `"Strictured Quert Language"` e significa `Linguagem de Consulta Estruturada.`

In [1]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect
import pandas as pd

In [2]:
engine = create_engine('sqlite:///:memory:')

#SQLite, vem naturalmente instalado no Google Colab.
#memory indica que estamos usando um banco de dados local.

## Para saber mais: bancos de dados e SQLAlchemy

Bancos de dados são sistemas que permitem armazenar, organizar e recuperar informações de forma estruturada e eficiente. Eles são amplamente usados em diversas áreas, desde gestão de negócios até pesquisa científica. Um banco de dados bem projetado melhora a eficiência e a precisão das operações.

Existem dois tipos principais de bancos de dados:

- **Relacionais**: armazenam dados em tabelas.
- **Não-relacionais (NoSQL – Not Only SQL)**: usam estruturas como documentos, grafos ou pares chave-valor.

Python oferece bibliotecas para trabalhar com bancos de dados, como SQLite, MySQL, PostgreSQL, Oracle e MongoDB. O **sqlite3** é comum para bancos SQLite: leve, incorporado e já disponível no Google Colab.

Para interagir com bancos relacionais, podemos usar a **SQLAlchemy**, uma biblioteca de mapeamento objeto-relacional (ORM). Ela permite trabalhar com objetos Python em vez de escrever diretamente SQL (Structured Query Language).

### Vantagens da SQLAlchemy:

- Código mais legível e fácil de manter.
- Operações em objetos Python, reduzindo erros.
- Suporte a consultas complexas em grandes conjuntos de dados.

Mais detalhes estão disponíveis na [documentação da SQLAlchemy](https://www.sqlalchemy.org/).

##Escrevendo em um banco de dados

In [3]:
url = 'https://media.githubusercontent.com/media/YuriArduino/Estudos_Pandas/refs/heads/data-tests/clientes_banco.csv'
dados = pd.read_csv(url)
dados.head()

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0     5008804     32   Ensino superior  União-estável                2   
1     5008805     32   Ensino superior  União-estável                2   
2     5008806     58      Ensino médio         Casado                2   
3     5008808     52      Ensino médio       Solteiro                1   
4     5008809     52      Ensino médio       Solteiro                1   

    Categoria_de_renda   Ocupacao  Anos_empregado  Rendimento_anual  \
0            Empregado      Outro              12          427500.0   
1            Empregado      Outro              12          427500.0   
2            Empregado  Segurança               3          112500.0   
3  Associado comercial     Vendas               8          270000.0   
4  Associado comercial     Vendas               8          270000.0   

   Tem_carro                   Moradia  
0          1       Apartamento alugado  
1          1       Apartamento alugado  
2          1  Casa/apartamento próprio  
3          0  Casa/apartamento próprio  
4          0  Casa/apartamento próprio

Na mesma linha inserimos uma vírgula e escrevemos a variável `engine`, que é o motor do banco. Por fim, escrevemos o parâmetro `index=False`.


>Lembrando que se não inserirmos esse parâmetro (`index=False`)sempre será criado uma nova coluna de index.



In [4]:
dados.to_sql('clientes', engine, index=False)

#'clientes' = nome da tabela

438463

In [5]:
inspector = inspect(engine)
inspector.get_table_names()

['clientes']

### Para saber mais: cláusulas SQL


**SQL (Structured Query Language** - Linguagem de Consulta Estruturada) é usada em bancos de dados relacionais para inserir, atualizar, consultar e gerenciar dados.

As **cláusulas SQL** são componentes fundamentais das instruções SQL. Elas permitem especificar como uma consulta ou operação deve ser executada, sendo usadas para **filtrar, classificar, agrupar e limitar** resultados.

As instruções SQL podem conter uma ou mais cláusulas. As mais comuns são:

* **SELECT**: especifica quais colunas consultar.
* **FROM**: indica as tabelas que serão consultadas.
* **WHERE**: filtra resultados com base em condições.
* **ORDER BY**: ordena resultados (crescente ou decrescente) por colunas.
* **GROUP BY**: agrupa resultados por colunas.
* **LIMIT**: limita o número de linhas retornadas.

**Exemplo de consulta SQL:**

```sql
SELECT nome, sobrenome, salario
FROM colaboradores
WHERE departamento = 'vendas'
```

* **SELECT**: define as colunas `nome`, `sobrenome` e `salario`.
* **FROM**: consulta a tabela `colaboradores`.
* **WHERE**: filtra resultados para o departamento `'vendas'`.

## Lendo uma consulta SQL

`query` é um padrão informal de boa prática, não uma regra rígida do SQLAlchemy ou do Python.

Normalmente, em projetos profissionais ou documentações, usam-se nomes descritivos que indicam a finalidade da consulta, como:

* `query` → padrão informal e muito comum
* `sql` → também comum, curto e direto
* `sql_query` → mais explícito, indica que é uma query SQL
* `command` ou `sql_command` → sugere uma instrução que será executada
* `stmt` (abreviação de statement) → usado em contextos mais técnicos

O importante é **manter consistência dentro do código** e escolher um nome que indique claramente que a variável contém uma instrução SQL.


In [6]:
query = ''

```
Lembrando que em SQL as cláusulas são escritas em caixa alta.

```

In [15]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda="Empregado"'

# *(asterisco) seleciona todas as informações da tabela 'clientes'
#onde a coluna 'Categoria_de_renda' é igual a "Empregado".

In [8]:
empregados = pd.read_sql(query, engine)

###Salvar como uma nova tabela

In [9]:
empregados.to_sql('empregados', con=engine, index=False)

#con especifica a conexão com o banco de dados (o engine).

226059

In [10]:
pd.read_sql_table('empregados', engine) #Ler a tabela inteira

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

```
O read_sql permite ler uma consulta e o read_sql_table uma tabela completa.
```

In [11]:
pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]

### Manipulando registros com SQLAlchemy

Para executar instruções SQL literais no Python, utilizamos a função `text` do SQLAlchemy:

```python
from sqlalchemy import text
```

#### Deletando um registro

```python
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()
```

**Passos principais:**

1. **Definir a consulta SQL:** `DELETE` remove o registro do cliente com `ID_Cliente=5008804`.
2. **Conectar ao banco:** `with engine.connect() as conn` abre e fecha automaticamente a conexão.
3. **Executar a consulta:** `conn.execute(text(query))` interpreta a string como SQL puro.
4. **Confirmar a transação:** `conn.commit()` salva permanentemente a alteração.

#### Atualizando um registro

```python
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()
```

* A consulta atualiza o grau de escolaridade do cliente identificado pelo ID.
* A conexão é aberta, a consulta executada e a transação confirmada da mesma forma que no DELETE.

> Esse processo garante manipulação segura e eficiente dos dados, mantendo consistência e integridade no banco.

---


In [13]:
from sqlalchemy import text

In [14]:
query = 'SELECT * FROM clientes'

In [16]:
pd.read_sql(query, engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008815     46   Ensino superior         Casado                2   
4          5112956     46   Ensino superior         Casado                2   
...            ...    ...               ...            ...              ...   
226054     6837905     43      Ensino médio         Casado                3   
226055     6837906     43      Ensino médio         Casado                3   
226056     6839936     34      Ensino médio         Casado                3   
226057     6840222     43      Ensino médio       Solteiro                1   
226058     6842885     51      Ensino médio         Casado                2   

       Categoria_de_renda          Ocupacao  Anos_empregado  Rendimento_anual  \
0               Empregado             Outro              12          427500.0   
1               Empregado             Outro              12          427500.0   
2               Empregado         Segurança               3          112500.0   
3               Empregado     Contabilidade               2          270000.0   
4               Empregado     Contabilidade               2          270000.0   
...                   ...               ...             ...               ...   
226054          Empregado             Outro               7          355050.0   
226055          Empregado             Outro               7          355050.0   
226056          Empregado  Construção Civil               5          135000.0   
226057          Empregado  Construção Civil               8          103500.0   
226058          Empregado            Vendas               3          121500.0   

        Tem_carro                   Moradia  
0               1       Apartamento alugado  
1               1       Apartamento alugado  
2               1  Casa/apartamento próprio  
3               1  Casa/apartamento próprio  
4               1  Casa/apartamento próprio  
...           ...                       ...  
226054          1  Casa/apartamento próprio  
226055          1  Casa/apartamento próprio  
226056          1  Casa/apartamento próprio  
226057          0  Casa/apartamento próprio  
226058          0  Casa/apartamento próprio  

[226059 rows x 11 columns]

##Atualizando um banco de dados

In [17]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [18]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52      Ensino médio       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

In [19]:
query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with engine.connect() as conn:
    result = conn.execute(text(query))
    conn.commit()

In [20]:
pd.read_sql_table('clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008805     32   Ensino superior  União-estável                2   
1          5008806     58      Ensino médio         Casado                2   
2          5008808     52   Ensino superior       Solteiro                1   
3          5008809     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438457     6840104     62      Ensino médio     Divorciado                1   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado         Segurança               3   
2       Associado comercial            Vendas               8   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438457          Pensionista             Outro               0   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               112500.0          1  Casa/apartamento próprio  
2               270000.0          0  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438457          135000.0          0  Casa/apartamento próprio  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  

[438462 rows x 11 columns]

#Exercício: manipulando um banco de dados

Você é responsável por criar um banco de dados local de clientes para uma instituição financeira. Temos o arquivo CSV com os dados de clientes.

Sua missão é:

Criar o banco de dados local com a biblioteca SQLAlchemy.
Escrever os dados do arquivo CSV neste banco de dados local.
Realizar três atualizações no banco de dados:
Atualizar o registro do cliente de ID 6840104 que teve o rendimento anual alterado para 300000.
Excluir o registro do cliente de ID 5008809, pois essa pessoa não possui mais conta na instituição financeira.
Criar um novo registro de cliente seguindo as especificações abaixo:
ID_Cliente: 6850985
Idade: 33
Grau_escolaridade: Doutorado
Estado_civil: Solteiro
Tamanho_familia: 1
Categoria_de_renda: Empregado
Ocupacao: TI
Anos_empregado: 2
Rendimento_anual: 290000
Tem_carro: 0
Moradia: Casa/apartamento próprio


> Dica importante: Para adicionar um(a) novo(a) cliente à tabela, utilize a cláusula INSERT INTO seguida do nome da tabela e depois especifique entre parênteses os nomes das colunas da tabela. Utilize a cláusula VALUES e, em seguida, passe entre parênteses os novos valores para esse novo registro. Certifique-se de que os valores estejam na ordem correta e no formato adequado para cada coluna.


In [21]:
import pandas as pd
import sqlalchemy

from sqlalchemy import text
from sqlalchemy import create_engine, MetaData, Table, inspect

engine = create_engine('sqlite:///:memory:')


url = 'https://media.githubusercontent.com/media/YuriArduino/Estudos_Pandas/refs/heads/data-tests/clientes_banco.csv'
dados_clientes = pd.read_csv(url)
dados.to_sql('dados_clientes', engine, index=False)

438463

In [22]:
pd.read_sql_table('dados_clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008809     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840104     62      Ensino médio     Divorciado                1   
438459     6840222     43      Ensino médio       Solteiro                1   
438460     6841878     22   Ensino superior       Solteiro                1   
438461     6842765     59      Ensino médio         Casado                2   
438462     6842885     51      Ensino médio         Casado                2   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458          Pensionista             Outro               0   
438459            Empregado  Construção Civil               8   
438460  Associado comercial            Vendas               1   
438461          Pensionista             Outro               0   
438462            Empregado            Vendas               3   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          135000.0          0  Casa/apartamento próprio  
438459          103500.0          0  Casa/apartamento próprio  
438460           54000.0          0          Mora com os pais  
438461           72000.0          0  Casa/apartamento próprio  
438462          121500.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]

In [24]:
sql_query = 'UPDATE dados_clientes SET Rendimento_anual=300000.0 WHERE ID_Cliente=6840104'
with engine.connect() as conn:
  result = conn.execute(text(sql_query))
  conn.commit()

In [25]:
sql_query = 'DELETE FROM dados_clientes WHERE ID_Cliente=5008809'
with engine.connect() as conn:
  result = conn.execute(text(sql_query))
  conn.commit()

In [26]:
sql_query = 'INSERT INTO dados_clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, ' \
        'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, ' \
        'Rendimento_anual, Tem_carro, Moradia) ' \
        'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
        '2, 290000, 0, "Casa/apartamento próprio")'

with engine.connect() as conn:
  result = conn.execute(text(sql_query))
  conn.commit()

In [27]:
pd.read_sql_table('dados_clientes', engine)

ID_Cliente  Idade Grau_escolaridade   Estado_civil  Tamanho_familia  \
0          5008804     32   Ensino superior  União-estável                2   
1          5008805     32   Ensino superior  União-estável                2   
2          5008806     58      Ensino médio         Casado                2   
3          5008808     52      Ensino médio       Solteiro                1   
4          5008810     52      Ensino médio       Solteiro                1   
...            ...    ...               ...            ...              ...   
438458     6840222     43      Ensino médio       Solteiro                1   
438459     6841878     22   Ensino superior       Solteiro                1   
438460     6842765     59      Ensino médio         Casado                2   
438461     6842885     51      Ensino médio         Casado                2   
438462     6850985     33         Doutorado       Solteiro                1   

         Categoria_de_renda          Ocupacao  Anos_empregado  \
0                 Empregado             Outro              12   
1                 Empregado             Outro              12   
2                 Empregado         Segurança               3   
3       Associado comercial            Vendas               8   
4       Associado comercial            Vendas               8   
...                     ...               ...             ...   
438458            Empregado  Construção Civil               8   
438459  Associado comercial            Vendas               1   
438460          Pensionista             Outro               0   
438461            Empregado            Vendas               3   
438462            Empregado                TI               2   

        Rendimento_anual  Tem_carro                   Moradia  
0               427500.0          1       Apartamento alugado  
1               427500.0          1       Apartamento alugado  
2               112500.0          1  Casa/apartamento próprio  
3               270000.0          0  Casa/apartamento próprio  
4               270000.0          0  Casa/apartamento próprio  
...                  ...        ...                       ...  
438458          103500.0          0  Casa/apartamento próprio  
438459           54000.0          0          Mora com os pais  
438460           72000.0          0  Casa/apartamento próprio  
438461          121500.0          0  Casa/apartamento próprio  
438462          290000.0          0  Casa/apartamento próprio  

[438463 rows x 11 columns]